day_night: no
directions: 'Office: West building W302'
font: my_font
font_size: M
office_hours: Monday to Friday, 10:00-16:00 hrs
theme: my_theme
extensions:
  academicons:
    enable: yes
  cms:
    branch: main
    local_backend: no
features:
  avatar:
    gravatar: no
    shape: circle
  comment:
    commento:
      url: ''
    disqus:
      shortname: ''
      show_count: yes
    giscus:
      category: ''
      category_id: ''
      repo: ''
      repo_id: ''
    provider: ''
  map:
    api_key: ''
    provider: mapnik
    zoom: 15
  math:
    enable: yes
  privacy_pack:
    enable: no
  repository:
    branch: main
    content_dir: content
    url: https://github.com/<username>/<repository>
  search:
    algolia:
      api_key: ''
      app_id: ''
      index_name: ''
      show_logo: no
    provider: wowchemy
  syntax_highlighter:
    theme_dark: dracula
    theme_light: github-light
footer:
  copyright:
    license:
      allow_commercial: no
      allow_derivatives: no
      enable: no
      share_alike: yes
header:
  navbar:
    align: l
    enable: yes
    highlight_active_link: yes
    show_day_night: no
    show_language: no
    show_logo: yes
    show_search: no
locale:
  address_format: de
  date_format: Jan 2, 2006
  time_format: 3:04 PM
marketing:
  analytics:
    baidu_tongji: ''
    google_analytics: UA-196914537-1
    google_site_verification: UA-196914537-1
    google_tag_manager: ''
    microsoft_clarity: ''
  seo:
    description: Webpage to promote the work of nicolas riveras munoz nriveras.
    local_business_type: ''
    org_name: ''
    site_type: Person
    twitter: wowchemy
  verification:
    baidu: ''
    google: ''
security:
  allow_frame: yes
Advanced:  
  address_format:
    de:
      delimiters:
        - ' '
        - ' '
        - ' '
        - ' '
        - ''
      order:
        - street
        - postcode
        - city
        - region
        - country
    en-gb:
      delimiters:
        - ', '
        - ', '
        - ', '
        - ''
      order:
        - street
        - city
        - region
        - postcode
    en-us:
      delimiters:
        - ', '
        - ', '
        - ' '
        - ''
      order:
        - street
        - city
        - region
        - postcode
    zh:
      delimiters:
        - ' '
        - ' '
        - ' '
        - ''
      order:
        - postcode
        - region
        - city
        - street
